export default [
	'Gore',
	'Disarmed',
	'Surprise Grandma',
	'Black Knight',
	'Good Boy',
	'Ratatouille',
	'Sick Dive',
	'Improper use of Adhesive',
	'Pustard',
	'Fernando is Fine',
	'DUCK!',
	'Staring Contest',
	'Peter Jackson Cameo',
	'Kicking ass for the lord',
	'Sucking face',
	'Stealth Expert',
	'Babysitting',
	'Hell Toupee',
	'Neti Cleansing',
	'Headlight',
	"Gnome'd",
	'Cure for Scoliosis',
	'Splitting Headache',
	'Playing the Organ',
	'Motherly Love'
];
/*
export generic [
	'Someone dies',
	'Tripping over nothing',
	'Weird coincidence',
	'Strange phone call',
	'Random power outage',
	'Flashing lights',
	'Abandoned Building',
	'Eyes in the Dark',
	'Trapped in Web',
	'Ankle Drag',
	'Jump Scare',
	'One-Liner',
	'Impaled',
	"T'n'A",
	'Nerd',
	'Excessive Drinking',
	'wilhelm scream',
	'Red-Necks',
	'Weird Basement or Attic',
	'Dead Animals',
	'Faked Death',
	'Gratuitous Gore',
	'Car Problems',
	'The Jerk Dies',
	'Chase scene',
	'Overturned Wheelchair',
	'Overbearing Music',
	'Shower Scene',
	'Fake jump scare',
	'Improper use of Sports Equipment',
	'Hearing Voices',
	'Title Drop'
];
*/
